### ISSUE TITLE
apache compliant licenses

### ISSUE THREAD

**Issue by fommil** [amplab/keystone#137]
If you're going to be part of Apache Spark you're going to have to leave the inclusion of the netlib-java natives up to the end user. They pull in LGPL code and have access to (potentially) proprietary binaries at runtime. This should be an easy thing for you to do, as we went through the whole process with SparkML back in the day :smile: Basically breeze-native / netlib-java:all should be "optional" in Apache speak.

**Comment by fommil** [comment]
btw, can you please make sure that you migrate over the docs that I wrote for getting Spark to work with native binaries? That should save anybody having to rewrite anything https://github.com/apache/spark/blob/master/docs/mllib-guide.md#dependencies

**Comment by etrain** [comment]
At the moment this project is not a part of Apache Spark, and there are a few libraries that we link to (but don't package or distribute) that are [L]GPL. I'm going to close this for now, but we can reopen once we start planning to ship with an Apache project.
