### ISSUE TITLE
Move Amazon example pipeline to master

### ISSUE THREAD

**Issue by etrain** [amplab/keystone#165]
We've got a cool pipeline for the Amazon product reviews dataset, let's move this to master!

**Comment by etrain** [comment]
cc @dcrankshaw

**Comment by tomerk** [comment]
Which pipeline do you want me to move over? The one that's the same as the 20newsgroups but with logistic regression instead of naive bayes at the end?

**Comment by etrain** [comment]
The data loader is also useful - but let's do logistic regression for some
variety.

**Comment by tomerk** [comment]
Do you also want the n-gram hashing amazon pipeline?

**Comment by etrain** [comment]
Closed by #166
