### ISSUE TITLE
Update website/API docs to reflect 0.2

### ISSUE THREAD

**Issue by etrain** [amplab/keystone#167]
Can we update the website with the latest API documentation and make sure that the syntax on the front-page is what's in the current newsgroups pipeline? 

I've got a few other cosmetic improvements that I'll make once this is done.

**Comment by etrain** [comment]
It probably also makes sense to start versioning the "api" directory in documentation like `api/0.2/` and maybe have a symlink which points `api/latest/` to `api/0.2/`. `api/latest` can then be the canonical place to find the documentation for the latest release.

**Comment by tomerk** [comment]
Silly question, but where can I find the code for the website?

**Comment by shivaram** [comment]
@tomerk Its in the gh-pages branch https://github.com/amplab/keystone/tree/gh-pages

**Comment by tomerk** [comment]
This was merged already so I'll close.
