### ISSUE TITLE
Misc Changes from keystone-vw-experiments

### ISSUE THREAD

**Issue by tomerk** [amplab/keystone#183]
Bring in bug fixes to:

- [x] LinearMapper cost function
- [x] CommonSparseFeatures
- [X] MatrixUtils

(etc. whatever I find hasn't made it into master yet)

**Comment by etrain** [comment]
@tomerk - just want to ping you on this so that we don't forget it. not sure what needs to be done with CommonSparseFeatures or LinearMapper (maybe the latter is good now?)

**Comment by shivaram** [comment]
I think CommonSparseFeatures had some fix to make it more scalable ? Did we already port that back ?

**Comment by tomerk** [comment]
Well the thing about CommonSparseFeatures is that we've made it more scalable for large numbers of features, but it's probably slower for small numbers of features. I could make two different nodes, or just use the implementation that's more scalable for large numbers of features.

**Comment by tomerk** [comment]
And then the LinearMapper thing is just a utility method to calculate loss, I'll make a PR.

**Comment by shivaram** [comment]
I'd say we should pick the more scalable one unless its much slower with smaller number of features. Do you have some numbers for what kind of slow down we are talking about ? Anyways its worth opening a PR for this and discussing it there

**Comment by etrain** [comment]
+1 for @shivaram's suggestion - if you could sketch out the two alternatives in the comments for the PR we can decide there.

**Comment by tomerk** [comment]
@shivaram: Nope I don't have timing numbers. The main difference is we fully sort each partition instead of doing an optimal get-top-k, so the per-partition time would be n log n instead of n log k.
(where n is number of features in that partition, and k is the total number of desired features)

**Comment by tomerk** [comment]
These have all gotten merged in at different points in time
