### ISSUE TITLE
Add weekly/pre-release integration tests

### ISSUE THREAD

**Issue by etrain** [amplab/keystone#189]
Before we cut a release and probably once a week, we should use the local spark cluster to run tests and look out for both statistical and computational performance regressions.

**Comment by etrain** [comment]
@shivaram - what do we want to capture here? My guess is end-to-end runtime and accuracy of at least CIFAR, VOC, and some version of TIMIT, and maybe a subset of ImageNet?

I think we can basically do this with a single shell script from jenkins and maybe some grep magic.

Shall we defer this to after 0.3.0 since the local spark cluster isn't up yet?

**Comment by shivaram** [comment]
Yes - CIFAR, Newsgroups20, VOC should all be in there. TIMIT and ImageNet might be trickier. I dont know how the local spark cluster availability relates our release dates, but we should run these once with 0.2 code and 0.3 code somewhere (say ec2) and tabulate the results.

**Comment by etrain** [comment]
At @shivaram 's suggestion I'm working on this in https://github.com/amplab/keystone-integration-tests

See the first pull request shortly.

**Comment by etrain** [comment]
A first cut of this has been merged. We will continue to improve separately.
