### ISSUE TITLE
Scala GMM and EncEval GMM don't give the same results

### ISSUE THREAD

**Issue by jrabary** [amplab/keystone#200]
I'm trying to compare the results of the two implementations of GMM estimator in keystoneml and they are very differents. As sample data, I use the `gmm_data.txt` available in spark source.
The EncEval version give results similar to scikit-learn GMM.

  
~~~
import nodes.learning.GaussianMixtureModelEstimator
import nodes.learning.external.{GaussianMixtureModelEstimator => EGMM}
import org.apache.spark.mllib.clustering.{GaussianMixtureModel => SGMM, GaussianMixture}
import org.apache.spark.mllib.linalg.Vectors
import org.apache.spark.{SparkConf, SparkContext}
import breeze.linalg.{DenseVector => BDV}


object GMM {

  def main (args: Array[String]) {
    val conf = new SparkConf()
      .setAppName("Extract Face Features")
      .setIfMissing("spark.master", "local[4]")
    val sc = new SparkContext(conf)
    val data = sc.textFile("spark/data/mllib/gmm_data.txt")
    val parsedData = data.map(s => BDV[Double](s.trim.split(' ').map(_.toDouble))).cache()

    val gmmEstimator = GaussianMixtureModelEstimator(2, 
        maxIterations = 100000,stopTolerance = 0d,
        smallVarianceThreshold = 0d)
    val gmmModel = gmmEstimator.fit(parsedData)

    val gmmEstimator2 = new EGMM(2)
    val gmmModel2 = gmmEstimator2.fit(parsedData)

    println("===================")
    println(gmmModel.means)
    println(gmmModel2.means)
    println("-------")
    println(gmmModel.variances)
    println(gmmModel2.variances)
    println("-----------")
    println(gmmModel.weights)
    println(gmmModel2.weights)

    sc.stop()
  }
}
~~~

**Comment by etrain** [comment]
Thanks for the bug report and code example - very helpful!

There are a few differences between the two implementations, one important one is the initialization strategy. The scala version is initialized via KMeans++, while the EncEval library version is initialized uniformly at random in data domain. A quick look also inidcates that the scala version actually achieves a better log-likelihood near the end of its iterations. -3.609 for EncEval vs. -3.564 for the Scala version.

**Comment by etrain** [comment]
Hey there - @tomerk and I took a look at this today.

**Comment by etrain** [comment]
Allowing the scala GMM to be initialized with the same method as the EncEval GMM has been enabled by #201 . Additionally, we've included a new unit test on the "+" dataset to ensure it is actually doing the right thing when the data really are a mixture of (diagonal-covariance) Gaussians.

I'm going to close this but feel free to reopen if you don't find the new initialization satisfactory.
