### ISSUE TITLE
Clean up build script

### ISSUE THREAD

**Issue by etrain** [amplab/keystone#218]
The build script is getting a little crusty, we should:

- Bump spark to 1.6.0
- Bump breeze to 0.12

Not sure what else. We may want to use this as an opportunity to test out the work being done in #189 , since both are pretty big changes and could affect accuracy, etc. of the example pipelines.

**Comment by etrain** [comment]
We also might as well bump the version number for Keystone when we do this.

**Comment by shivaram** [comment]
Just want to add that this also needs the regression tests to make sure we aren't using some specific behavior in Spark 1.3 etc.

**Comment by etrain** [comment]
We need to update the `Makefile` to include the latest version number as well.
