### ISSUE TITLE
Broadcast W, b in RandomCosineFeatures

### ISSUE THREAD

**Issue by shivaram** [amplab/keystone#230]
This affects performance when we have large number of random features and was found by @ericmjonas and @Vaishaal 

cc @etrain

**Comment by etrain** [comment]
As @Vaishaal also notes, we could simply generate these on the Executor side and save the network bandwidth. Relies on seeding the RNG exactly the same on all nodes and duplicates work, but should shave some end-to-end runtime.

**Comment by etrain** [comment]
Ignoring the prposal above (generate on the executor side) 

@shivaram - can you describe what the issue with not explicitly broadcasting is? Are we sending the whole matrix once per executor or something? I understand that W and b are getting serialized with the task, but are the tasks not getting broadcast now?

**Comment by shivaram** [comment]
So from what I remember - we needed to do this in the suncast case and @tomerk added it https://github.com/ericmjonas/suncast/commit/90df2b8b4cb98198bad052a3c2c38081ca50f2f7 (which is partly why I assigned it to him)

I think the root cause was something either around task deserialization taking too long or the the task broadcast being repeated when do somethings iteratively. @tomerk / @ericmjonas do you have any ideas on why you did this ?

Irrespective I don't think its a bad idea to use a broadcast variable when its really large amount of data. It lets you control the lifecycle much better.

**Comment by tomerk** [comment]
Totally forgot I wrote that. At the time I was probably under the impression that the matrix was getting transferred over the network once per task, but that might not have been the case.

**Comment by ericmjonas** [comment]
Doesn't this behavior also potentially change between spark 1.3 and 1.6?
Suncast only targets 1.6 now

**Comment by shivaram** [comment]
Ok I don't mind closing this issue as won't fix - but I'll feel better about it if we do two things
(a) Run suncast with Spark 1.6 after switching it back to the non-broadcasted version
(b) Make sure the TIMIT pipeline with 200k features using the `Pipeline.gather` + random cosine features doesn't suffer in performance

**Comment by tomerk** [comment]
Hmm either way we should probably add the node @Vaishaal wrote for generating the random features matrix on the executors. I just need to know what changes still need to be made to turn that node into a PR if you guys want me to.

**Comment by shivaram** [comment]
@Vaishaal 's code is at https://raw.githubusercontent.com/Vaishaal/ckm/whitening/keystone_pipeline/src/main/scala/nodes/stats/SeededCosineRandomFeatures.scala

**Comment by tomerk** [comment]
Right, he'd mentioned that there were some changes he wanted me to make to turn that into a pull request, I just don't know what they are.

Sent from Outlook Mobile




On Wed, Feb 17, 2016 at 4:34 PM -0800, "Shivaram Venkataraman" <notifications@github.com> wrote:












@Vaishaal 's code is at https://raw.githubusercontent.com/Vaishaal/ckm/whitening/keystone_pipeline/src/main/scala/nodes/stats/SeededCosineRandomFeatures.scala

**Comment by Vaishaal** [comment]
Look at
https://github.com/amplab/keystone/blob/master/src/main/scala/nodes/stats/CosineRandomFeatures.scala

You can pass in the distribution you want to sample from.

If you could add that that would be great :D

**Comment by tomerk** [comment]
So the risk with allowing users to pass in a `Rand[Double]` is that if they haven't initialized a seed properly the node could end up buggy and non-deterministic (assuming `Rand[Double]` is even serializable). What I could do is make the node take parameters for the distribution to use, if you have any specific ones you'd like to see available.

**Comment by tomerk** [comment]
Alternatively I could make it take a (RandBasis => Rand[Double]) if users don't have non-serializable dependencies in the closure if that works better.

**Comment by etrain** [comment]
I think it's fine to assume that users don't have non-serializable
dependencies in the closure. In general we can assume that our users are
spark users and are used to dealing with these kinds of issues. I may
regret these words ;)

**Comment by shivaram** [comment]
Closed by #245
