### ISSUE TITLE
Update keystone-ec2 scripts to pass environment variables into build

### ISSUE THREAD

**Issue by etrain** [amplab/keystone#262]
They keystone-ec2 scripts should build against the correct versions of spark/hadoop for the cluster that is launched (e.g. `SPARK_VERSION=1.3.1 HADOOP_VERSION=2.0.0 sbt/sbt assembly`

**Comment by shivaram** [comment]
Fixed by https://github.com/shivaram/spark-ec2/commit/36d998c76a0750513948bad48801528425d96063

**Comment by etrain** [comment]
Nice - thanks @shivaram !
