### ISSUE TITLE
Put vlfeat on s3

### ISSUE THREAD

**Issue by etrain** [amplab/keystone#268]
We depend on an oxford website in our build script which went down earlier today. I expect it to come back, but it is worthwhile to create a mirror of it on S3 and depend on that directly.

Thanks for reporting @zhaozhang !

**Comment by shivaram** [comment]
Just to clarify we should put both vlfeat (from http://www.vlfeat.org/download/vlfeat-0.9.20-bin.tar.gz ) and enceval (http://www.robots.ox.ac.uk/~vgg/software/enceval_toolkit/downloads/enceval-toolkit-1.1.tar.gz) on S3

**Comment by etrain** [comment]
Yup - two birds, thanks @shivaram
