### ISSUE TITLE
TF-IDF?

### ISSUE THREAD

**Issue by Refefer** [amplab/keystone#299]
I see the TermFrequency transformer and have found some ghosts of `IDFCommonSparseFeatures` around the web, but it doesn't appear this transform exists with Keystone anymore.

Any approaches folks suggest for tackling TF-IDF transforms?

**Comment by etrain** [comment]
Here's the implementation of `IDFCommonsparseFeatures` that you're referring to: https://github.com/tomerk/keystone/blob/ampcamp-6/src/main/scala/nodes/nlp/IDFCommonSparseFeatures.scala

I haven't tried compiling it against the latest version of KeystoneML, but I would expect that it basically works. Feel free to send a PR if you use it and find it useful.

**Comment by etrain** [comment]
Closing this for now - feel free to reopen if you need help with the above.
